version: 2
updates:
  # Update pnpm packages weekly
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: '*'
        update-types:
          - 'version-update:semver-major'

  # Update GitHub Actions monthly
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
    ignore:
      - dependency-name: '*'
        update-types:
          - 'version-update:semver-major'
